[build]
    base = "web"
    publish = "build"
    environment = { REACT_APP_DOMAIN="whispering-sea-50524.herokuapp.com", REACT_APP_API_WEBSOCKET_PORT="443" }

[[redirects]]
    from = "/*"
    to = "/"
    force = true
